### ISSUE TITLE
Improve UI/UX of Adding a new User to a group.( + prevent refresh when user added)

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/distrideochat#11]

**Comment by vasusharma7** [comment]
Working on this - updating page without refresh.

**Comment by vasusharma7** [comment]
Added Auto refresh on - 
1. Rooms when created
2 . Users when added
3 . Instant Chat messages as they are sent.

Please check the PR https://github.com/Pranav2612000/milaap/pull/43

**Comment by vasusharma7** [comment]
UI/UX still to be improved.

**Comment by naman-modi** [comment]
Done.
