### ISSUE TITLE
Feature : Notification on receiving new message

### ISSUE THREAD

**Issue by savannahar68** [Pranav2612000/distrideochat#123]
With current implementation user has no idea if a new message is received or not.

We can change the message icon to show the count of new messages received or pop a notification on receiving new message

**Comment by vasusharma7** [comment]
Added this feature . Its on [this](https://github.com/Pranav2612000/distrideochat/tree/message-notification) branch.

One enhancement left : When the user is already on the message view, then also the badge icon appears.
I tired adding event on scroll to bottom to remove the badge then, but was getting some errors.

**Comment by savannahar68** [comment]
@vasusharma7 can you try fixing/adding the enhancement?
Also, make sure only new messages count is displayed.

If possible please drop a screenshot here.

**Comment by vasusharma7** [comment]
Sure @savannahar68 
New message count is displayed. But it gets lost after refresh as redux state is lost.
Haven't implemented redux-persist or any other state maintenance across refreshes yet.Will do that also soon.

**Comment by vasusharma7** [comment]
[](url)
![Screenshot from 2020-07-14 08-39-41](https://user-images.githubusercontent.com/40715071/87379391-c1d1fd00-c5ad-11ea-8d09-1cc9f749c650.png)
![Uploading Screenshot from 2020-07-14 08-39-45.png…]()

**Comment by vasusharma7** [comment]
@savannahar68 
Can we skip showing the badge if the user is already on message View ?
No doubt the notifications and sound will still be there ?

**Comment by savannahar68** [comment]
> New message count is displayed. But it gets lost after refresh as redux state is lost.

That is valid behavior

> Can we skip showing the badge if the user is already on message View ?

Yes, this looks more ideal

**Comment by vasusharma7** [comment]
Solved / Fixed the message badge when message view is opened !

Have merged dev-vs with message notification branch
