### ISSUE TITLE
Add Firebase Authentication

### ISSUE THREAD

**Issue by naman-modi** [Pranav2612000/distrideochat#15]
Need firebase for Google sign in to be implemented. It will be easy for users to sign in. @Pranav2612000, Let me know what you need after signin for the database.

**Comment by AnupNair08** [comment]
Google Sign In working
Tested on Google Chrome
Issues with Brave Browser

**Comment by naman-modi** [comment]
Which branch?
And the credentials remain the same right?

**Comment by Pranav2612000** [comment]
> Google Sign In working
> Tested on Google Chrome
> Issues with Brave Browser

Great. We havent tried the video calling on brave browser too... 

What issues are you facing?

**Comment by AnupNair08** [comment]
Google sign In pop-up crashes 
Searching for a fix

**Comment by Pranav2612000** [comment]
Great. Is it just for this site or is it a common issue for many sites. If the fix isn't trivial. Let's not focus on this now. Brave isn't a commonly used browser.

**Comment by AnupNair08** [comment]
Seems like Brave blocks third party cookies and it needs to be enabled in the privacy settings for it to work.

**Comment by naman-modi** [comment]
Not required now. 
Users need to self-register on DistrideoChat.
