### ISSUE TITLE
change room icons on left-sidebar

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/distrideochat#23]
![image](https://user-images.githubusercontent.com/20909078/82158998-fe80c100-98a8-11ea-980d-004c69174f98.png)

Change these icons by something better.

**Comment by veddandekar** [comment]
We should probably allow the user to set this group icon, once the group settings in the right panel are done.
We can decide which w ould be the default. Our current icons are from - https://coreui.io/v1/demo/AngularJS_Demo/#!/icons/simple-line-icons

Tbh, none of them seem good enough to represent a room. How about icon-cup?

**Comment by naman-modi** [comment]
Resolved.
