### ISSUE TITLE
Replace the "CoreUI" image in title bar.

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/distrideochat#25]
![image](https://user-images.githubusercontent.com/20909078/82159115-a39b9980-98a9-11ea-96b0-fe40899c3da7.png)

**Comment by veddandekar** [comment]
Milaap needs a logo.
@AnupNair08 considering that you have some prior designing exprience, any intuitive ideas?

**Comment by AnupNair08** [comment]
I'll draft a few designs

**Comment by AnupNair08** [comment]
Please review the drafts for the logo
@Pranav2612000  @veddandekar  @naman-modi 
![logo1](https://user-images.githubusercontent.com/54449305/82463274-40dd1480-9ada-11ea-8627-512d5609aab6.PNG)

**Comment by naman-modi** [comment]
Ref2 looks great!

**Comment by veddandekar** [comment]
I really like Ref 2 too!

**Comment by naman-modi** [comment]
It's done.
![logo](https://user-images.githubusercontent.com/38180263/82809125-017f4100-9ea9-11ea-899e-8cdc764551c1.png)
