### ISSUE TITLE
Discussion: Display the name of the current room in which the user is.

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/distrideochat#27]
Can't think of an appropriate position. What do you guys suggest?

**Comment by Pranav2612000** [comment]
Possible options: 1)The top title bar(where dashboard and Add Friend currently is)
                             2) the bar where the list, messages, settings icons are shown.

**Comment by veddandekar** [comment]
Option 1 sounds more appealing to me

**Comment by Pranav2612000** [comment]
Others? Should we go with this then?

**Comment by naman-modi** [comment]
Displayed as a notification, when user enters the room.
