### ISSUE TITLE
Discussion: Dashboard page

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/distrideochat#28]
What are some ideas for the dashboard page. Do we need one or should we remove it?

What I think is we can display the health monitoring statistics of the current user( obtained through fit api, screen time)(CoreUI has some good graphs) and some health tips, suggestions, precautions, advices and the latest activity of the user/ missed notifications.

@AnupNair08 @naman-modi @ vasusharma @veddandekar

**Comment by veddandekar** [comment]
We could add in a list for any online scheduled sessions the user may have.

Further, we could allow the user to segregate his groups into something like 'work' and 'personal' to better show him a breakdown of how he spents his time. Maybe even add in a 'focus' mode at the top that blocks notifications from all groups previously marked as 'personal'

**Comment by naman-modi** [comment]
<h3>In the centre, related to meetings/rooms</h3>
On the centre of the dashboard we require the following options:
<ul>
<li>To <b><i>schedule</b></i> or <b><i>start</b></i> or <b><i>join</b></i> Video Sync from particular video streaming website(eg: Youtube) </li>
<li>To <b><i>schedule</b></i> or <b><i>start</b></i> or <b><i>join</b></i> for viewing a webpage</li>
<li>To <b><i>schedule</b></i> or <b><i>start</b></i> or <b><i>join</b></i> a room for meeting, wherein screen sharing should be possible.</li>
</ul>
Please note that:
<ol>
<li>If the user selects <b><i>schedule</b></i>, should be redirected to Calendar for scheduling a meet/room.</li>
<li>If the user selects <b><i>join</b></i>, the user should be asked to enter to room/meet ID, or the link.</li>
<li>The to-be meetings (like which are scheduled from the current time to 7 days) should be displayed on the dashboard, so accordingly the user can <b><i>Start</i></b> or <b><i>Join</i></b>.</li>
</ol> 
<h3>On the right panel, statistics regarding heath</h3>
The first thing that should be seen is the amount of <b><i>time already spent</i></b> on that day, and how many <b><i>watch-minutes left</b></i>. <br>
The following graphs can be displayed:
<ul>
<li>On X axis: the days, and on Y axis: Amount of time per day (bar graph)</li>
<li>Something regarding the amount of workout to be done for gaining particular watch minutes.</li>
</ul>
Below these, we can keep flashing the tips of doing workout.<br><br>
We can also have a look at [Healthrx](https://www.healthrx.co.in/)  app, and check if something from there can be integrated onto the dashboard. <br><br>
<b>Please don't directly start working on UI, I'll design and send it, then we can have discussions on it.</b>

**Comment by naman-modi** [comment]
Done.
