### ISSUE TITLE
Discussion: Room View

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/distrideochat#29]
Ideas about the UI visible when a room is entered -

There is a lot of space wasted at the center(where the videos are displayed) when no call is in progress. What I have in mind is having something like skype does with the user video playing at the back with buttons on front- 
![image](https://user-images.githubusercontent.com/20909078/82159603-05113780-98ad-11ea-83da-90486dda8c3f.png)

I like the idea of displaying the list of all the users in the list tab in right sidebar - 
![image](https://user-images.githubusercontent.com/20909078/82159655-70f3a000-98ad-11ea-825c-9b500162f6f0.png)
with the users differentiated into 3 categories through the UI and arranged category-wise - those in a call in the group, users online, users offline, but in the group.

Any other suggestions for improving the room UI

@naman-modi @veddandekar @AnupNair08

**Comment by naman-modi** [comment]
So, this will be displayed when the user is not in the call but is invited for the call, right?

**Comment by Pranav2612000** [comment]
> So, this will be displayed when the user is not in the call but is invited for the call, right?

When a user enters a room.

**Comment by naman-modi** [comment]
>When a user enters a room.

And the call is not yet started, right?

**Comment by naman-modi** [comment]
Done.
