### ISSUE TITLE
Change colour scheme to purple.

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/distrideochat#36]

**Comment by Pranav2612000** [comment]
check out route for inbuilt themes and colors - /#/theme/colors refer to

**Comment by naman-modi** [comment]
1. Switching to Purple (specifically #714684 -  just checked from their website), which is the theme of their website would be useful for us. 
2. Anyone (@Pranav2612000 @veddandekar @AnupNair08 @vasusharma7 ) aware of their UI Components if available on open source?
