### ISSUE TITLE
Add support for JWT/Cookies

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/distrideochat#38]
As of now, we are using localstorage to directly store username and are using this to send request to backend. Replace this by JWTs / Cookies which is secure. Will require adding middleware to backend, and passing the JWT through headers.

**Comment by naman-modi** [comment]
@Pranav2612000 Any specific middleware you have in mind?

**Comment by Pranav2612000** [comment]
JWTs are easily implemented using readymade npm packages. We'll need to add a middleware express route to extract the information from the Token. I don't have much experience with cookies. But it shouldn't be much difficult.

**Comment by naman-modi** [comment]
Okay, it works.

**Comment by vasusharma7** [comment]
I will add this !

**Comment by vasusharma7** [comment]
See PR #58

**Comment by Pranav2612000** [comment]
@vasusharma7 

Adding the line "Fixed #PR no" automatically links this issue to the PR. Which makes it easier for others to view the PRs submitted for this issue, plus on merging the PR, the issue gets closed automatically.
