### ISSUE TITLE
Landing page required

### ISSUE THREAD

**Issue by veddandekar** [Pranav2612000/distrideochat#45]
Not our current focus, but we will definitely need on down the road.
Putting this up rn to remind everyone to be on the look out for good templates/packages for the same.

**Comment by naman-modi** [comment]
@veddandekar For now, it will be the sign-in page, right?

**Comment by veddandekar** [comment]
> @veddandekar For now, it will be the sign-in page, right?

Yes, works for now

**Comment by naman-modi** [comment]
Done.
