### ISSUE TITLE
Room Change Doesn't take place sometimes

### ISSUE THREAD

**Issue by vasusharma7** [Pranav2612000/distrideochat#59]
Sometimes, the room is not changed though it is clicked on .
The URL changes but the updated room name is not passed to Control.js from DefaultAside.js.
Experienced very less times usually  just after logging in or after refresh.
try 
User 1
Password 1
It has ample rooms to recreate the issue.

**Comment by vasusharma7** [comment]
https://drive.google.com/open?id=1z4Oildnsi9H9qDmOuMM9gLzWGwR645hc

**Comment by vasusharma7** [comment]
Please tell if anyone else is also facing this issue

**Comment by savannahar68** [comment]
I guess this is fixed now with Pranav's changes
It was a bug in code

This issue can be closed if @Pranav2612000 approves.
