### ISSUE TITLE
Remove dead video streams

### ISSUE THREAD

**Issue by veddandekar** [Pranav2612000/distrideochat#7]
Currently just freezes/turns black.

**Comment by Pranav2612000** [comment]
This wil require experimentation to find exact event on which we remove streams. Sometimes closing a connection at one end, gives out an error on the other side which may cause the other side to reconnect(It could be great if someone could confirm this).

**Comment by veddandekar** [comment]
Just a heads up, once PR #18 is merged some slight modification _may_ be required to the logic at line 53 of "Rooms.js"

**Comment by Pranav2612000** [comment]
Line numbers may change. What exactly will we need to change?

**Comment by veddandekar** [comment]
PR has been rejected, so I think we can work directly on this instead.

One possible solution is to add peer ID as the id to the HTML video element. We can then simply remove the video element from DOM when the user disconnects from the room.

**Comment by Pranav2612000** [comment]
Working on this and #20 which is similar.

**Comment by Pranav2612000** [comment]
Fixed.
