### ISSUE TITLE
Join by link

### ISSUE THREAD

**Issue by veddandekar** [Pranav2612000/distrideochat#70]
Users should be able to enter a room directly using a link.

Refer - https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

**Comment by naman-modi** [comment]
The user should also given an option to copy the link.

**Comment by AnupNair08** [comment]
Tried working on this feature
The Web Share API doesn't support major browsers. Found it to not work on Chrome, Brave and Firefox.
Any alternatives?
@veddandekar

**Comment by veddandekar** [comment]
We could probably do something like, if Share API 
is supported(mainly mobile browsers) then use that. If not, the use clipboard API to show the link and allow copy to clipboard instead.

This shows how we can easily add a fallback - https://css-tricks.com/how-to-use-the-web-share-api/

Our fallback could be be the much more widely supported clipboard API - https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

**Comment by naman-modi** [comment]
Have a look at this: https://w3c.github.io/web-share/ 
- Try this on your phone, and not on a laptop

Found it over here: https://web.dev/web-share/

Documentation: https://www.w3.org/TR/web-share/

So it doesn't work on ***Chrome***, but works on ***Chrome(Android)***

**Comment by AnupNair08** [comment]
Please check #79 
Desktop users can copy link and supported browsers can use Web Share

**Comment by veddandekar** [comment]
Good work @AnupNair08 !
