### ISSUE TITLE
Change design of creating rooms

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/distrideochat#71]
Currently, new rooms are created when a user adds a friend/another user to the room. This creates problems when adding support to add anonymous users, add more than 1 user to the room etc. 
The design is being changed according to the following example - 
A logged in user can create a new room. This adds a new room entry in the database. The logged in user can now add other users through either the room UI by entering their usernames(this button needs to be created), or by sharing the room link. When na anonymous user visits the link. The app will check if the room exists( by quering the database), if it doesnt redirect to 404, then it'll check if the user has a valid token. If he doesn't then redirect the anonymous user to a page which asks for a temporary username(with an option to login) after logging in the user can then enter the room.

**Comment by naman-modi** [comment]
Fixed.
