### ISSUE TITLE
Change to a PWA

### ISSUE THREAD

**Issue by naman-modi** [Pranav2612000/distrideochat#72]
For seamless experience of the users on mobile phones, once the backend is completely ready, its needs to converted to a PWA.

**Comment by savannahar68** [comment]
@Pranav2612000 @naman-modi 
Anyone working on this?
If no I can take this

**Comment by naman-modi** [comment]
No one yet, because we want to fix other features/core video calling functionalities first, as we are still working on the back-end. We have decided it to keep it for the last. 

@Pranav2612000 @veddandekar Please correct me if I am wrong.
