### ISSUE TITLE
Dark theme is not properly integrated across all the components

### ISSUE THREAD

**Issue by savannahar68** [Pranav2612000/distrideochat#87]
Issues :

* Chat section is not visible properly
* Chat styling is affected because of dark theme
* Side bar not properly displayed
* Message Setting icon not displayed until hover
* Chat section send button out of window
* Things typed in send window(chat section) not visible
--------
![image](https://user-images.githubusercontent.com/20986069/83606736-b7c4e380-a597-11ea-8413-2611813a284f.png)
----
![image](https://user-images.githubusercontent.com/20986069/83606853-ddea8380-a597-11ea-802c-ebb8522080c7.png)
----
![image](https://user-images.githubusercontent.com/20986069/83606890-ee9af980-a597-11ea-8831-f35b57c85b64.png)

**Comment by AnupNair08** [comment]
Please check #91 @savannahar68 
Mentioned bugs have been fixed.
Please review the changes
![Capture](https://user-images.githubusercontent.com/54449305/83949615-7f94fd80-a842-11ea-9672-06cd56763db9.PNG)
![2](https://user-images.githubusercontent.com/54449305/83949620-815ec100-a842-11ea-8dd5-ea831dea6965.PNG)
![3](https://user-images.githubusercontent.com/54449305/83949621-81f75780-a842-11ea-89da-652325bf0aa0.PNG)

**Comment by savannahar68** [comment]
@AnupNair08 can we have sender's chat at right and receiving chat at left?

**Comment by AnupNair08** [comment]
@savannahar68 fixed the part
Also new chats are rendered without scrolling
![4](https://user-images.githubusercontent.com/54449305/83962476-5fedeb80-a8bb-11ea-9c35-82a183e1e37f.PNG)

**Comment by savannahar68** [comment]
@AnupNair08 LGTM
